project_id = "ctolbfzqhvamzdbnywyc"

[functions.parse-email-order]
verify_jwt = false

[functions.receive-forwarded-email]
verify_jwt = false

[functions.fetch-gmail-orders]
verify_jwt = false

[functions.fetch-pending-orders]
verify_jwt = false

[functions.fetch-sales-velocity]
verify_jwt = false

[functions.sync-google-sheets]
verify_jwt = false

[functions.chat]
verify_jwt = false
